SELECT item.CODE as [ITEM CODE], unit.BARCODE as Barcode, item.DESC_ENG as [ITEM NAME],
	(tblStock.Qty/unit.PACK_SIZE) as [STOCK], item.DESC_ARB, CONCAT(item.PERIOD, ' ', item.PERIODTYPE) AS PERIOD,
	unit.UNIT_CODE, GEN_TAX_MASTER.TaxRate, INV_ITEM_TYPE.DESC_ENG as [TYPE], INV_ITEM_CATEGORY.DESC_ENG as CATEGORY,
	INV_ITEM_GROUP.DESC_ENG AS [GROUP], INV_ITEM_TM.DESC_ENG AS TRADEMARK, item.TaxId, item.HASSERIAL,
	tblStock.supplier_id, PAY_SUPPLIER.DESC_ENG as Supplier
FROM INV_ITEM_DIRECTORY as item 
JOIN INV_ITEM_DIRECTORY_UNITS AS unit ON item.CODE = unit.ITEM_CODE
LEFT JOIN tblStock ON item.CODE = tblStock.Item_id
LEFT JOIN INV_ITEM_TYPE ON item.TYPE = INV_ITEM_TYPE.CODE
LEFT JOIN INV_ITEM_CATEGORY ON item.CATEGORY = INV_ITEM_CATEGORY.CODE
LEFT JOIN INV_ITEM_GROUP ON item.[GROUP] = INV_ITEM_GROUP.CODE
LEFT JOIN INV_ITEM_TM ON item.TRADEMARK = INV_ITEM_TM.CODE
LEFT JOIN GEN_TAX_MASTER ON item.TaxId = GEN_TAX_MASTER.TaxId
LEFT JOIN PAY_SUPPLIER ON tblStock.supplier_id = PAY_SUPPLIER.CODE
ORDER BY [ITEM NAME] ASC

/*SELECT  DISTINCT INV_ITEM_DIRECTORY.CODE AS [ITEM CODE], INV_ITEM_DIRECTORY_UNITS.BARCODE AS Barcode, 
INV_ITEM_DIRECTORY.DESC_ENG AS [ITEM NAME],STOCK_TABLE.STOCK AS 'STOCK',
INV_ITEM_DIRECTORY.DESC_ARB,CONCAT(INV_ITEM_DIRECTORY.PERIOD,' ',INV_ITEM_DIRECTORY.PERIODTYPE) AS PERIOD,INV_ITEM_DIRECTORY_UNITS.UNIT_CODE, 
GEN_TAX_MASTER.TaxRate, INV_ITEM_TYPE.DESC_ENG AS TYPE, 
INV_ITEM_CATEGORY.DESC_ENG AS CATEGORY, INV_ITEM_GROUP.DESC_ENG AS [GROUP], INV_ITEM_TM.DESC_ENG AS TRADEMARK, 
INV_ITEM_DIRECTORY.TaxId, INV_ITEM_DIRECTORY.HASSERIAL 

FROM INV_ITEM_DIRECTORY INNER JOIN INV_ITEM_DIRECTORY_UNITS ON INV_ITEM_DIRECTORY.CODE = INV_ITEM_DIRECTORY_UNITS.ITEM_CODE
LEFT OUTER JOIN 

(SELECT INV_ITEM_DIRECTORY.CODE,
(ISNULL(OPNQUANTITY.QNTY,0)+(ISNULL(STOCKADJ.STKADJQNTY,0))+
ISNULL(PUR.PURCHASE,0)+(ISNULL(STOCKIN.STKIN,0))-(ISNULL(STOCKOUT.STKOUT,0))-ISNULL(PUR_RETURN.P_RETURN,0)
-ISNULL(SALES.TOTAL_SALES,0)+ISNULL(SALES_RETURN.TOTAL_SALES_RETURN,0)) 
AS STOCK from INV_ITEM_DIRECTORY  LEFT OUTER JOIN INV_STK_TRX_DTL 
ON INV_ITEM_DIRECTORY.CODE=INV_STK_TRX_DTL.ITEM_CODE 
LEFT OUTER JOIN (SELECT  ITEM_CODE,(SUM(INV_STK_TRX_DTL.QUANTITY)) 
AS QNTY 
FROM INV_STK_TRX_DTL 
WHERE DOC_TYPE='INV.STK.OPN' GROUP BY ITEM_CODE)AS OPNQUANTITY 
ON OPNQUANTITY.ITEM_CODE=INV_ITEM_DIRECTORY.CODE 
LEFT OUTER JOIN (SELECT  ITEM_CODE,(SUM(INV_STK_TRX_DTL.QUANTITY)) 
AS STKADJQNTY FROM INV_STK_TRX_DTL WHERE DOC_TYPE='INV.STK.ADJ' 
GROUP BY ITEM_CODE)AS STOCKADJ 
ON STOCKADJ.ITEM_CODE=INV_ITEM_DIRECTORY.CODE 
LEFT OUTER JOIN (SELECT  ITEM_CODE,(SUM(INV_STK_TRX_DTL.QUANTITY)) AS STKIN FROM INV_STK_TRX_DTL 
WHERE DOC_TYPE='INV.STK.IN' GROUP BY ITEM_CODE)AS STOCKIN ON STOCKIN.ITEM_CODE=INV_ITEM_DIRECTORY.CODE 
LEFT OUTER JOIN (SELECT  ITEM_CODE,(SUM(INV_STK_TRX_DTL.QUANTITY)) AS STKOUT 
FROM INV_STK_TRX_DTL WHERE DOC_TYPE='INV.STK.OUT' GROUP BY ITEM_CODE)AS STOCKOUT 
ON STOCKOUT.ITEM_CODE=INV_ITEM_DIRECTORY.CODE LEFT OUTER JOIN(SELECT ITEM_CODE,(SUM(INV_PURCHASE_DTL.QTY_RCVD)) 
AS PURCHASE FROM INV_PURCHASE_DTL WHERE DOC_TYPE!='LGR.PRT' and INV_PURCHASE_DTL.FLAGDEL!='False' GROUP BY ITEM_CODE) 
AS PUR ON PUR.ITEM_CODE=INV_ITEM_DIRECTORY.CODE LEFT OUTER JOIN (SELECT ITEM_CODE,(SUM(INV_PURCHASE_DTL.QTY_RCVD)) 
AS P_RETURN FROM INV_PURCHASE_DTL WHERE DOC_TYPE='LGR.PRT' GROUP BY ITEM_CODE) AS PUR_RETURN 
ON PUR_RETURN.ITEM_CODE=INV_ITEM_DIRECTORY.CODE 
LEFT OUTER JOIN (SELECT ITEM_CODE,SUM(INV_SALES_DTL.QUANTITY) 
AS TOTAL_SALES FROM INV_SALES_DTL WHERE DOC_TYPE!='SAL.CSR'  AND INV_SALES_DTL.FLAGDEL!='False' 
GROUP BY ITEM_CODE) AS SALES ON SALES.ITEM_CODE=INV_ITEM_DIRECTORY.CODE 
LEFT OUTER JOIN (SELECT ITEM_CODE,SUM(INV_SALES_DTL.QUANTITY) 
AS TOTAL_SALES_RETURN FROM INV_SALES_DTL WHERE DOC_TYPE='SAL.CSR'  
GROUP BY ITEM_CODE) AS SALES_RETURN ON SALES_RETURN.ITEM_CODE=INV_ITEM_DIRECTORY.CODE) 


AS STOCK_TABLE ON STOCK_TABLE.CODE=INV_ITEM_DIRECTORY.CODE LEFT OUTER JOIN INV_ITEM_TYPE 
ON INV_ITEM_DIRECTORY.TYPE=INV_ITEM_TYPE.CODE LEFT  OUTER JOIN INV_ITEM_CATEGORY 
ON INV_ITEM_DIRECTORY.CATEGORY=INV_ITEM_CATEGORY.CODE LEFT OUTER JOIN INV_ITEM_GROUP 
ON INV_ITEM_DIRECTORY.[GROUP]=INV_ITEM_GROUP.CODE LEFT OUTER JOIN INV_ITEM_TM 
ON INV_ITEM_DIRECTORY.TRADEMARK=INV_ITEM_TM.CODE LEFT OUTER JOIN GEN_TAX_MASTER ON GEN_TAX_MASTER.TaxId=INV_ITEM_DIRECTORY.TaxId*/